default:
  # Radius of the inner label, unit does not matter but has to match the one used for outer radius
  inner_radius: 3.5
  # Radius of the entire disc
  outer_radius: 11.8
  # Number of beats the disc has
  number_beats: 144
  # Bandwidth used for meanshift clustering the tracks
  bandwidth: 8
  # How far to look around each pixel when finding connected components in the image
  search_distance: 1
  # Average width of each track as relative distance between center and outer border
  track_width: 0.01845976
  # Relative position of the innnermost track from center to outer border
  first_track: 0.325
  # Total number of tracks on the disc
  n_tracks: 36
  # Low threshold for canny algorithm
  canny_low: 100
  # High threshold
  canny_high: 255
  # Mappings of tracks to midi codes
  track_mappings:
    1: 43
    2: 45
    3: 47
    4: 48
    5: 50
    6: 52
    7: 53
    8: 54
    9: 55
    10: 57
    11: 59
    12: 60
    13: 61
    14: 62
    15: 63
    16: 64
    17: 65
    18: 66
    19: 67
    20: 68
    21: 69
    22: 70
    23: 71
    24: 72
    25: 73
    26: 74
    27: 75
    28: 76
    29: 77
    30: 78
    31: 79
    32: 80
    33: 81
    34: 82
    35: 83
    36: 84
